ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo
ARG BASE_IMAGE
ARG ROS_DISTRO
FROM ${BASE_IMAGE}

SHELL [ "/bin/bash","-c" ]

#Install Dependent Packages
RUN . /root/.venv/bin/activate \
&& python -m pip install --upgrade pip \
&& python -m pip install whill
